// <auto-generated />
using System;
using FormulaForge.ApiService.Persistence.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormulaForge.ApiService.Persistence.Postgres.Migrations
{
    [DbContext(typeof(FormulaForgeDbContext))]
    [Migration("20260222180243_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormulaForge.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BooleanScalarValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BooleanTimeSeriesValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecimalScalarValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecimalTimeSeriesValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntegerScalarValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntegerTimeSeriesValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
