// <auto-generated />
using System;
using FormulaForge.ApiService.Persistence.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormulaForge.ApiService.Persistence.Postgres.Migrations
{
    [DbContext(typeof(FormulaForgeDbContext))]
    [Migration("20260314162912_InitializeDatabase")]
    partial class InitializeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormulaForge.Domain.Entities.BooleanScalarValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BooleanScalarValueEntity");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.BooleanTimeSeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BooleanTimeSeriesEntity");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.BooleanTimeSeriesEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TimeSeriesId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TimeSeriesId");

                    b.ToTable("BooleanTimeSeriesEntry");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.DecimalScalarValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DecimalScalarValueEntity");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.DecimalTimeSeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DecimalTimeSeriesEntity");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.DecimalTimeSeriesEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TimeSeriesId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TimeSeriesId");

                    b.ToTable("DecimalTimeSeriesEntry");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.IntegerScalarValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IntegerScalarValueEntity");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.IntegerTimeSeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IntegerTimeSeriesEntity");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.IntegerTimeSeriesEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TimeSeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TimeSeriesId");

                    b.ToTable("IntegerTimeSeriesEntry");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.BooleanScalarValueEntity", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.Project", null)
                        .WithMany("BooleanScalarValues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.BooleanTimeSeriesEntity", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.Project", null)
                        .WithMany("BooleanTimeSeriesValues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.BooleanTimeSeriesEntry", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.BooleanTimeSeriesEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("TimeSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.DecimalScalarValueEntity", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.Project", null)
                        .WithMany("DecimalScalarValues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.DecimalTimeSeriesEntity", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.Project", null)
                        .WithMany("DecimalTimeSeriesValues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.DecimalTimeSeriesEntry", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.DecimalTimeSeriesEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("TimeSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.IntegerScalarValueEntity", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.Project", null)
                        .WithMany("IntegerScalarValues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.IntegerTimeSeriesEntity", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.Project", null)
                        .WithMany("IntegerTimeSeriesValues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.IntegerTimeSeriesEntry", b =>
                {
                    b.HasOne("FormulaForge.Domain.Entities.IntegerTimeSeriesEntity", null)
                        .WithMany("Entries")
                        .HasForeignKey("TimeSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.BooleanTimeSeriesEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.DecimalTimeSeriesEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.IntegerTimeSeriesEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FormulaForge.Domain.Entities.Project", b =>
                {
                    b.Navigation("BooleanScalarValues");

                    b.Navigation("BooleanTimeSeriesValues");

                    b.Navigation("DecimalScalarValues");

                    b.Navigation("DecimalTimeSeriesValues");

                    b.Navigation("IntegerScalarValues");

                    b.Navigation("IntegerTimeSeriesValues");
                });
#pragma warning restore 612, 618
        }
    }
}
